# Generated by Django 3.0.3 on 2020-02-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=128, verbose_name='Author Email')),
                ('text', models.CharField(max_length=100, verbose_name='Message Text')),
                ('created_ts', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_ts', models.DateTimeField(blank=True, null=True, verbose_name='Update Date')),
            ],
            options={
                'verbose_name': 'API Message',
                'verbose_name_plural': 'API Messages',
            },
        ),
    ]
