# Generated by Django 3.0.3 on 2020-02-24 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='updated_ts',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='Update Date'),
            preserve_default=False,
        ),
    ]
